name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch, tag or SHA to release from"
        required: true
        default: "master"

jobs:
  pure-built-distributions:
    name: Build pure wheels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install build dependencies
        run: python -m pip install -U pip setuptools wheel
      - name: Build wheels
        run: python setup.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: ./dist/*.whl

  source-distribution:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Build source distribution
        run: python setup.py sdist
      - name: Store the source distribution
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: dist
          retention-days: 4

  publish:
    needs:
      - pure-built-distributions
      - source-distribution
    runs-on: ubuntu-latest
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v2
        with:
          name: python-package-distributions
          path: dist/
      - name: What will we publish?
        run: ls -l dist
      - name: Publish
        if: github.event.inputs.branch != ''
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
          print_hash: true
