name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: pip
      - name: Install build dependencies
        run: |
          python -m pip install -U pip 
          python -m pip install -e '.[dev]'
      - name: Build
        run: python -m build
      - name: Check
        run: twine check --strict dist/*
      - name: What will we publish?
        run: ls -l dist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          print-hash: true
